"""Interactive processes — pywinpty/ConPTY.

The powershell tool pipes stdin from nowhere, so anything that asks a question
mid-run (an ssh host-key confirmation, a credential prompt, an installer, a
REPL) blocks until the timeout kills it. This spawns the program on a real
ConPTY pseudo-console and answers its prompts from a script the model supplies
up front. ConPTY is confirmed present and working on Windows 10
(KernelBase.dll exports CreatePseudoConsole/ClosePseudoConsole/
ResizePseudoConsole/CreatePseudoConsoleAsUser) and exercised end to end through
`pywinpty` (a clean prebuilt wheel, no compiler needed): spawn, read, write and
exit-code capture all confirmed, including a full expect-then-send round trip
against a real prompting child process.

Three properties of ConPTY that shape the code, none of them oversights:
  * `pywinpty`'s `read()` is blocking-only — confirmed live, an attempt at a
    non-blocking read raised TypeError immediately — and takes no timeout. So
    the read runs on its own thread feeding a queue, and this module's loop
    polls that queue against a deadline to get timeout-per-step behaviour.
  * Windows has no signal concept for a child like this, so `signal_status` in
    the response is always None — `exit_status` alone is the whole story.
  * **`secret: true` protects the transcript, not the console.** ConPTY is
    deliberately built to behave exactly like a real console from the child's
    point of view, which means the *child* owns its echo setting
    (`SetConsoleMode`/`ENABLE_ECHO_INPUT`) and the host side cannot turn it off
    out from under it. In practice this rarely matters, because real secret
    prompts — an `ssh` password prompt, `Read-Host -AsSecureString` — suppress
    their own echo before reading. It was confirmed to matter with a child that
    deliberately does not (a plain `input()`): the sent secret genuinely
    appeared in the raw ConPTY output. Mitigated as defence in depth rather
    than guaranteed: every literal `send` value from a `secret: true` step is
    scrubbed out of incoming buffer content the moment it arrives, before it
    can reach either pattern-matching or the transcript.

Commands are wrapped as `["cmd.exe", "/c", command]` — deliberately not
`pwsh`/`powershell.exe`, to avoid re-introducing the `-Command` quoting
complexity already dealt with in core/powershell.py. Ask for PowerShell as the
command itself if a given task needs it; cmd.exe is only the thin wrapper.

No ConPTY resize handling: this is a scripted expect/send tool, not a live
human-facing terminal, so there is no window for the caller to resize.

**Know what the transport is, because this tool handles passwords.** pywinpty
does not hand pty output back in-process: `PtyProcess.__init__` opens a
listening TCP socket on an ephemeral 127.0.0.1 port, starts a reader thread
that connects back to it, and `accept()`s the first connection (read its
ptyprocess.py — this is not an implementation detail that can be configured
away). Everything the child prints therefore crosses a loopback socket with no
authentication on it, and `accept()` takes whoever connects first, so another
local process could in principle win that race and receive the transcript
instead. Anything typed at a prompt that the program echoes is in that stream.

This is the same class of exposure core/kernel.py goes to the trouble of
CurveZMQ for, and it cannot be fixed from here — it is pywinpty's design, and
the alternative implementations are worse. Treat `secret: true` as protecting
the *returned transcript*, which is its documented job, and not the wire.

A step's answer can come from three places: `send` (a literal string, the
model writes it directly), `send_env` (the NAME of an environment variable —
`os.environ` is read for the actual value locally, in this process, never by
the model), or `send_secret` (the NAME of a `gopass` entry — resolved locally
via `gopass show <name>`, never by the model). `send_env`/`send_secret` exist
for the same reason as the Linux/Mac originals: a literal `send` means the
actual secret has to be generated by the model to appear in the tool call at
all — round-tripping it through Anthropic's API twice (once in, once out)
before `secret: true` ever gets a chance to redact anything, which only ever
covered what came back afterward.

`send_secret` uses `gopass` (gopasspw/gopass), not the original `pass` — the
real `pass` shell script (getopt/tree/gpg/git glued together) has no native
Windows build at all and normally only runs under WSL/Git-Bash/Cygwin, which
would make this tool depend on a POSIX layer this fork otherwise has no
reason to require. `gopass` is a from-scratch Go reimplementation, explicitly
positioned by its own maintainers as **"a drop-in replacement for pass"**,
ships a genuine native Windows binary (`winget install gopass.gopass`,
`choco install gopass`, or `scoop install gopass`), and mirrors the exact
subcommands this module needs (`show <name>`, `ls --flat`) closely enough
that `_resolve_reply`/`_select_entry_prompt` below need no Windows-specific
branch beyond the binary name. By default it encrypts with GPG and versions
with git, same as `pass` — `winget install GnuPG.Gpg4win` alongside it is
gopass's own documented Windows setup, not an extra dependency invented
here. Windows Credential Manager (the `cmdkey`/DPAPI route via
`System.Security.Cryptography.ProtectedData`) was evaluated and rejected for
`send_secret` specifically, for the same reason the Mac fork rejected
Keychain-via-`security` and the Linux original rejected `secret-tool`: it
would mean teaching this tool a second, platform-specific credential
backend, when this project's own secret-handling convention
(`config.toml`'s `token_env`/`api_key_env` indirection) already commits to
`pass`-compatible tooling as the one source-of-truth backend, consistently,
across every fork.

`_select_entry_prompt()` (the `"?"` sentinel / first-reference-refusal
prompt) diverges from the Linux/Mac originals in one deliberate way: those
walk `$PASSWORD_STORE_DIR`'s `*.gpg` files directly off disk specifically to
avoid `pass ls`'s tree-drawing output losing a nested entry's folder
structure. `gopass ls --flat` already prints one full path per entry with no
tree-drawing at all, so there is nothing to work around here, and no reason
to independently reason about wherever `gopass` happens to keep its store on
a given Windows machine (its own default store location is not the fixed,
documented `~/.password-store` convention `pass` guarantees).

Requires:  pip install pywinpty  (API verified against 3.0.5)
"""

import asyncio
import json
import os
import queue
import re
import subprocess
import threading
import time

from core.output import clip, strip_ansi

TOOLS = [
    {
        "name": "interactive_run",
        "description": (
            "Run a command that PROMPTS for input, answering its prompts from a "
            "script. Use this instead of powershell whenever a program asks a "
            "question mid-run — password challenges, ssh host-key confirmation, "
            "'Are you sure? [y/N]', winget/installer prompts, or a REPL — since "
            "the powershell tool has no stdin and will simply hang. Each step "
            "waits for a regex to appear, then sends a line. For a password or "
            "token specifically, use a step's `send_env`/`send_secret` "
            "instead of `send` — the real value is read locally (from an "
            "environment variable, or from a `gopass` password-store entry "
            "for genuine at-rest encryption) and never has to be written into "
            "this call at all, unlike a literal `send`, which the user has "
            "to tell you and you have to write down to use. Returns JSON "
            "with the terminal transcript and the exit status."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": (
                        "Shell command to spawn on a pty, e.g. "
                        "'ssh user@host uptime'."
                    ),
                },
                "steps": {
                    "type": "array",
                    "description": (
                        "Prompt/response pairs, applied in order. Omit for a "
                        "command that only needs a pty and no answers."
                    ),
                    "items": {
                        "type": "object",
                        "properties": {
                            "expect": {
                                "type": "string",
                                "description": (
                                    "Regex to wait for, e.g. 'password:' or "
                                    "'\\[y/N\\]'."
                                ),
                            },
                            "send": {
                                "type": "string",
                                "description": (
                                    "Literal line to send once it matches. "
                                    "Exactly one of `send`/`send_env`/"
                                    "`send_secret` is required per step. Use "
                                    "this for non-secret input (a username, "
                                    "'yes', a menu choice) — for a password "
                                    "or token, use `send_env`/`send_secret` "
                                    "instead so the real value never has to "
                                    "be written into this call at all."
                                ),
                            },
                            "send_env": {
                                "type": "string",
                                "description": (
                                    "Name of an environment variable — its "
                                    "value is read locally and sent, never "
                                    "written into this tool call. Use for a "
                                    "password/token/passphrase: the user "
                                    "sets the variable ahead of time (out of "
                                    "band, never told to you), you only "
                                    "ever name it here. Always treated as "
                                    "secret in the returned transcript, "
                                    "regardless of the `secret` field. "
                                    "Errors clearly if the named variable "
                                    "isn't set, before spawning anything."
                                ),
                            },
                            "send_secret": {
                                "type": "string",
                                "description": (
                                    "Name of a `gopass` (a native-Windows, "
                                    "GPG-backed password manager, drop-in "
                                    "compatible with `pass`) entry — "
                                    "resolved locally via `gopass show "
                                    "<name>` and sent, never written into "
                                    "this tool call. Prefer this over "
                                    "`send_env` when genuine at-rest "
                                    "encryption matters. Errors clearly if "
                                    "`gopass`/the named entry isn't "
                                    "available, before spawning anything. "
                                    "Don't know which entry to use? Pass "
                                    "the literal string \"?\" instead of a "
                                    "real name — this returns a fixed, "
                                    "ready-to-relay prompt built from the "
                                    "real vault contents (\"please select "
                                    "the cred name I need to use:\" plus "
                                    "every real entry), not something to "
                                    "guess at or compose yourself."
                                ),
                            },
                            "secret": {
                                "type": "boolean",
                                "description": (
                                    "Redact this step's `send` response from "
                                    "the returned transcript. Only meaningful "
                                    "for a literal `send` — `send_env`/"
                                    "`send_secret` are always redacted "
                                    "unconditionally, since their entire "
                                    "point is keeping the real value out of "
                                    "anything you see."
                                ),
                            },
                        },
                        "required": ["expect"],
                    },
                },
                "timeout": {
                    "type": "integer",
                    "description": (
                        "Seconds to wait for each prompt and for the program to "
                        "finish (default 30)."
                    ),
                },
            },
            "required": ["command"],
        },
    }
]

_TOOL_NAMES = {t["name"] for t in TOOLS}
_MAX_TRANSCRIPT = 12000
_DEFAULT_TIMEOUT = 30
# How often the pump loop re-checks its deadline while waiting on the queue —
# short enough that a timeout is never overshot by more than this.
_POLL_INTERVAL = 0.2
# How long to wait for the child to actually be gone after terminate/close,
# before reporting exit_status as-is rather than blocking any longer.
_EXIT_GRACE = 5.0

# How long `send_secret`'s `gopass show` subprocess gets before giving up —
# see `_resolve_reply`'s own docstring for why this exists at all (an
# unanswerable Gpg4win pinentry dialog, with no way for this call to answer
# it, would otherwise hang for the full interactive_run timeout).
_SEND_SECRET_TIMEOUT = 30

# Entry names that have already been explicitly presented AND re-referenced
# once, for the life of this process — same incident/rationale as the
# Linux/Mac originals: a direct, correct entry name must still be refused on
# its first-ever reference, so nothing skips straight to using the sole vault
# entry with no selection prompt at all. A module-level set, not a function
# default, because it has to persist across separate `_run()` calls within
# the same running process to mean anything.
_confirmed_secret_entries: set[str] = set()


def handles(name: str) -> bool:
    return name in _TOOL_NAMES


async def execute(name: str, tool_input: dict) -> str:
    if name != "interactive_run":
        return json.dumps({"error": f"unknown process tool {name!r}"})
    return await asyncio.to_thread(_run, tool_input)


def _resolve_reply(step: dict) -> tuple[str, bool, str | None]:
    """Return (reply_text, is_secret, error) for one step.

    Exactly one of `send`/`send_env`/`send_secret` must be present —
    anything else (zero, or more than one) is a caller error, returned as
    `error` rather than silently guessing which one was meant. `send_env`/
    `send_secret` always come back with `is_secret=True`; a literal `send`
    respects the step's own `secret` field (default `False`), matching this
    tool's existing behavior for that case unchanged.

    `send_secret` shells out to `gopass show <name>` with a bounded timeout
    (`_SEND_SECRET_TIMEOUT`, 30s), not an unbounded wait — if the GPG key
    isn't already cached in `gpg-agent`, Gpg4win's own pinentry dialog can
    pop up on the user's own desktop, independent of this call entirely, and
    answering it takes real human time. There is no terminal or dialog
    *here* to answer it either way, so this would otherwise hang for the
    full `interactive_run` timeout on top of whatever the REAL command's own
    steps needed, indistinguishable from a genuine hang. The error message
    says so explicitly rather than just "timed out" — unlock the key once,
    manually, first, which caches it for a while afterward and lets
    subsequent calls succeed silently.
    """
    sources = [k for k in ("send", "send_env", "send_secret") if k in step]
    if len(sources) == 0:
        return "", False, "must include one of `send`, `send_env`, `send_secret`"
    if len(sources) > 1:
        return "", False, f"only one of `send`/`send_env`/`send_secret` allowed, got {sources}"

    if "send" in step:
        return str(step["send"]), bool(step.get("secret")), None

    if "send_env" in step:
        var_name = str(step["send_env"])
        value = os.environ.get(var_name)
        if value is None:
            return "", False, f"environment variable {var_name!r} is not set"
        return value, True, None

    entry_name = str(step["send_secret"])
    if entry_name == "?" or entry_name not in _confirmed_secret_entries:
        # First reference to this exact name (or an explicit "?") — refuse
        # to use it yet, REGARDLESS of whether it's real, correct, or the
        # only entry that exists. Recording it here means the NEXT call
        # that names this same entry is treated as the confirmed one — so
        # a real task still only takes two calls total (present, then use),
        # not a repeated prompt every single time the same entry comes up
        # later in the same session.
        _confirmed_secret_entries.add(entry_name)
        return "", False, _select_entry_prompt()

    try:
        result = subprocess.run(
            ["gopass", "show", entry_name],
            capture_output=True,
            text=True,
            timeout=_SEND_SECRET_TIMEOUT,
            check=False,
        )
    except FileNotFoundError:
        return "", False, (
            "`gopass` is not installed (see the module docstring — "
            "`winget install GnuPG.Gpg4win` then `winget install "
            "gopass.gopass`)"
        )
    except subprocess.TimeoutExpired:
        return "", False, (
            f"`gopass show {entry_name!r}` did not return within "
            f"{_SEND_SECRET_TIMEOUT}s — likely waiting on a GPG passphrase "
            "prompt with nothing here to answer it. Unlock the key once, "
            "manually, first — gpg-agent caches it for a while afterward, "
            "and this call will then succeed silently."
        )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown error"
        return "", False, f"`gopass show {entry_name!r}` failed: {detail}{_available_entries_hint()}"
    first_line = result.stdout.splitlines()[0] if result.stdout else ""
    return first_line, True, None


def _select_entry_prompt() -> str:
    """The exact, hardcoded text returned when a step uses `"send_secret": "?"`
    — the caller's explicit way of saying "I need a credential here but don't
    know which vault entry to use." Builds a fixed-format message from the
    REAL entries in the vault; nothing about the wording is left to whatever
    composes the final reply to the user.

    Uses `gopass ls --flat` — one full entry path per line, no tree-drawing
    — rather than walking a store directory directly the way the Linux/Mac
    originals do for `pass`: `gopass` has no single guaranteed store
    location the way `pass` guarantees `~/.password-store`, and `--flat`
    already solves the exact "nested entry loses its folder structure"
    problem those originals were working around by hand.
    """
    try:
        result = subprocess.run(
            ["gopass", "ls", "--flat"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except FileNotFoundError:
        return "`gopass` is not installed — nothing to select"
    except subprocess.TimeoutExpired:
        return "`gopass ls --flat` did not return in time — nothing to select"
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown error"
        return f"`gopass ls --flat` failed: {detail} — nothing to select"
    entries = sorted(line.strip() for line in result.stdout.splitlines() if line.strip())
    if not entries:
        return "the password store is empty — nothing to select"
    return "please select the cred name I need to use:\n" + "\n".join(entries)


def _available_entries_hint() -> str:
    """Appended to a `send_secret` failure message: the real list of entry
    NAMES currently in the vault (never their values — `gopass ls` is a
    pure listing, needs no passphrase and touches no encrypted content at
    all). Exists specifically so a wrong or made-up entry name doesn't just
    fail blind — the caller sees what's actually there immediately, in the
    same error, rather than needing a separate round trip to ask "what do
    you even have?" Best-effort — if `gopass ls` itself fails for any
    reason, the base error above is still returned on its own.
    """
    try:
        result = subprocess.run(
            ["gopass", "ls", "--flat"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
    except Exception:
        return ""
    if result.returncode != 0 or not result.stdout.strip():
        return ""
    return f"\n\nEntries actually in the vault:\n{result.stdout.strip()}"


class _Reader:
    """Runs PtyProcess.read() on its own thread and feeds a queue.

    pywinpty's read() blocks until there is data or the pty closes — there is
    no timeout parameter to give it, so a caller that wants to honour a
    per-step deadline has to poll a queue instead of calling read() directly
    on the main thread. `None` on the queue is the EOF sentinel.
    """

    def __init__(self, proc):
        self._proc = proc
        self._queue: queue.Queue = queue.Queue()
        self.eof = False
        self._thread = threading.Thread(target=self._pump, daemon=True)
        self._thread.start()

    def _pump(self):
        try:
            while True:
                data = self._proc.read(4096)
                # `continue`, NOT `break`: an empty string here does not mean
                # EOF. pywinpty's reader thread substitutes the literal marker
                # b'0011Ignore' whenever the underlying pty read came back with
                # nothing (ptyprocess.py: `pty.read(...) or '0011Ignore'`), and
                # PtyProcess.read turns that marker back into ''. It is a
                # routine "no data this time", not a closed terminal.
                #
                # Real EOF is unambiguous and arrives as an exception: the
                # reader thread sends a zero-length frame, recv returns b'',
                # and read() raises EOFError, which the handler below catches.
                # Treating '' as EOF made this loop stop at the first idle
                # moment — before the prompt being waited for had appeared —
                # so a step would report steps_matched: 0 with a truncated
                # transcript and no error at all. That fails intermittently,
                # depending on timing, which is why a single quick round trip
                # can pass and a real session cannot.
                if not data:
                    continue
                self._queue.put(data)
        except EOFError:
            pass
        except Exception as e:  # the pty vanished under us mid-read
            self._queue.put(f"\n[reader error: {e}]")
        self._queue.put(None)

    def get(self, timeout: float) -> str | None:
        """One chunk, or None if the queue was empty for the whole timeout.
        The EOF sentinel also surfaces as None — callers distinguish the two
        with `.eof`, set the instant the sentinel is actually seen."""
        try:
            item = self._queue.get(timeout=timeout)
        except queue.Empty:
            return None
        if item is None:
            self.eof = True
            return None
        return item


def _run(tool_input: dict) -> str:
    try:
        import winpty
    except ImportError:
        return json.dumps(
            {
                "error": "pywinpty is not installed — `pip install pywinpty` "
                "to enable interactive_run on Windows"
            }
        )

    command = tool_input.get("command", "")
    if not command.strip():
        return json.dumps({"error": "no command provided"})

    steps = tool_input.get("steps") or []
    timeout = int(tool_input.get("timeout") or _DEFAULT_TIMEOUT)

    # Resolve every step's actual reply text AND whether it counts as secret
    # up front, before spawning anything — a missing env var, a not-yet-
    # confirmed/missing `gopass` entry, or `gopass` itself being absent is a
    # configuration error the caller should see immediately, not something
    # that surfaces only after a real program has already been left
    # mid-prompt (ssh half-connected, an installer half-run) by a step
    # further down the list. Same up-front-resolution shape as the Linux/Mac
    # originals.
    resolved_replies: list[tuple[str, bool]] = []
    for i, step in enumerate(steps):
        reply, is_secret, error = _resolve_reply(step)
        if error:
            return json.dumps({"error": f"step {i}: {error}"})
        resolved_replies.append((reply, is_secret))

    try:
        # cmd.exe /c is a thin wrapper so `command` can use shell syntax; it
        # is not a requirement to use cmd.exe-specific features.
        proc = winpty.PtyProcess.spawn(["cmd.exe", "/c", command])
    except Exception as e:
        return json.dumps({"error": f"could not spawn command: {e}"})

    reader = _Reader(proc)
    buffer = ""
    transcript: list[str] = []
    matched = 0
    timed_out_at = None
    # Best-effort defense-in-depth for any secret step — see the module
    # docstring for why this is a mitigation, not a guarantee, on Windows.
    # Seeded with EVERY resolved secret value up front (not appended step by
    # step as each is sent), so a value is scrubbed from incoming buffer
    # content from the very first chunk read onward — including, in
    # principle, an earlier prompt's own output, not just whatever arrives
    # after the step that actually sends it.
    secrets_to_scrub: list[str] = [
        reply for reply, is_secret in resolved_replies if is_secret
    ]

    def _scrub(text: str) -> str:
        for secret in secrets_to_scrub:
            if secret:
                text = text.replace(secret, "***")
        return text

    def pump_until(
        pattern: "re.Pattern[str]", deadline: float
    ) -> tuple[str, "re.Match[str] | None"]:
        """Waits for `pattern` in the accumulating buffer, or the deadline.

        Returns ("matched"|"eof"|"timeout", match) — the three outcomes the
        step loop below needs to tell apart; there is no library doing it for
        us, so all three are spelled out. The match object is handed back rather than the caller
        re-running `search`: it is the same result by construction, and
        returning it means there is no second call whose None case has to be
        reasoned about.
        """
        nonlocal buffer
        while True:
            found = pattern.search(buffer)
            if found:
                return "matched", found
            if reader.eof:
                return "eof", None
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                return "timeout", None
            chunk = reader.get(min(remaining, _POLL_INTERVAL))
            if chunk:
                buffer += _scrub(chunk)

    try:
        for step, (reply, is_secret) in zip(steps, resolved_replies, strict=True):
            pattern = re.compile(str(step.get("expect", "")))
            deadline = time.monotonic() + timeout
            outcome, match = pump_until(pattern, deadline)

            if outcome == "timeout":
                timed_out_at = str(step.get("expect", ""))
                transcript.append(buffer)
                buffer = ""
                break
            if outcome == "eof" or match is None:
                # The program finished before this prompt ever appeared —
                # not a timeout, just an early exit. Same distinction
                # an early exit does.
                timed_out_at = None
                transcript.append(buffer)
                buffer = ""
                break

            transcript.append(buffer[: match.end()])
            buffer = buffer[match.end() :]
            try:
                # "\r" alone, not "\r\n". Writing to a ConPTY is synthesised
                # typing, and the Enter key is a carriage return — the console
                # is what turns that into a line terminator for the program
                # reading it. Sending "\r\n" types Enter *and then* a Ctrl-J,
                # leaving a spare newline in the input buffer that the next
                # read consumes as an empty line. A single-step script cannot
                # show this (nothing reads again), which is exactly why it
                # survives a quick round-trip test; a two-step script answers
                # its second prompt with "" before the model's real answer
                # arrives.
                proc.write(reply + "\r")
            except EOFError:
                # The pty closed between matching the prompt and answering it
                # — seen live against cmd.exe's own `set /p` under emulation.
                # Not a timeout (we did match); just nothing left to send to.
                timed_out_at = None
                break
            # `secrets_to_scrub` was already seeded with every resolved
            # secret value before spawning (see above) — no per-step append
            # needed here anymore, `is_secret` alone decides how THIS one
            # line renders in the transcript.
            transcript.append("***\n" if is_secret else reply + "\n")
            matched += 1

        # Drain whatever the program prints after the last answer, mirroring
        # the drain that follows the last answered prompt.
        drain_deadline = time.monotonic() + timeout
        while not reader.eof and time.monotonic() < drain_deadline:
            chunk = reader.get(min(drain_deadline - time.monotonic(), _POLL_INTERVAL))
            if chunk:
                buffer += _scrub(chunk)
        transcript.append(buffer)
    finally:
        # Two calls, and both are needed. `terminate` stops the child (it goes
        # straight to TerminateProcess here — pywinpty's `kill` is os.kill,
        # and on Windows os.kill is TerminateProcess for anything that is not
        # CTRL_C_EVENT/CTRL_BREAK_EVENT, so the SIGINT it names is not a
        # polite interrupt). `close` releases what PtyProcess allocated per
        # call: two sockets and a reader thread. Without it those are only
        # reclaimed when __del__ happens to run, and the reader thread holds a
        # reference to the process object, so a wedged read pins the lot for
        # the lifetime of this long-running app.
        for label, cleanup in (("terminate", proc.terminate), ("close", proc.close)):
            try:
                cleanup(force=True)
            except Exception as e:
                print(f"[processes] proc.{label} failed (ignored): {e}")

    # Bounded, because pywinpty's own wait() is `while isalive(): sleep(0.1)`
    # with no timeout — if the child somehow survived TerminateProcess above,
    # an unguarded wait() would hang this tool call forever and quietly break
    # the `timeout` this tool advertises. exitstatus is None while alive, which
    # is a truthful answer for a process that would not die.
    exit_deadline = time.monotonic() + _EXIT_GRACE
    while proc.isalive() and time.monotonic() < exit_deadline:
        time.sleep(0.05)

    return json.dumps(
        {
            "transcript": clip(strip_ansi("".join(transcript)), _MAX_TRANSCRIPT),
            "steps_matched": matched,
            "steps_total": len(steps),
            "exit_status": proc.exitstatus,
            "signal_status": None,  # Windows has no signal status for a child
            "timed_out_waiting_for": timed_out_at,
        }
    )
